---
- name: launch EC2 instance
  hosts: localhost
  vars:
    instance_type: t3a.micro
  vars_prompt:
    - name: image
      prompt: enter ami id, enter to use default
      default: "ami-0cea098ed2ac54925"
    - name: security_group_id
      prompt: enter security group id
      private: no
    - name: vpc_subnet_id
      prompt: enter subnet id
      private: no
    - name: key_name
      prompt: enter AWS keypair
      private: no
  tasks:
    - name: launching ec2 instance
      amazon.aws.ec2_instance:
        name: "wordpress"
        key_name: "{{ key_name }}"
        instance_type: "{{ instance_type }}"
        image_id: "{{ image }}"
        wait: yes
        state: running
        vpc_subnet_id: "{{ vpc_subnet_id }}"
        security_group: "{{ security_group_id }}"
        network:
          assign_public_ip: true
      register: ec2

    - name: wait for ssh to come up
      wait_for:
        host: "{{ ec2.instances[0].public_dns_name }}"
        port: 22
        state: started

    - meta: refresh_inventory