---
- name: begin wordpress deployment
  hosts: tag_Name_wordpress
  become: yes
  remote_user: ec2-user
  vars:
    domain_regex: '^((?!-))(xn--)?[a-z0-9][a-z0-9-_]{0,61}[a-z0-9]{0,1}\.(xn--)?([a-z0-9\-]{1,61}|[a-z0-9-]{1,30}\.[a-z]{2,})$'
    mysql_user_id: 88
    mysql_group_id: 88
    mysql_db_dir: /var/db/mysql
    mysql_image: mysql
    mysql_user: wordpress
    mysql_db: wordpress
    wordpress_path: /var/www/html
    wp_admin_user: "wpadmin"
    weather_url: "https://wttr.in/Chicago?format=3"
    wp_cli_name: wp
  vars_files:
    - secrets.yml
  vars_prompt:
    - name: wp_domain
      prompt: enter domain name
      private: no
  environment:
    PATH: "/usr/local/bin:{{ ansible_env.PATH }}"
  pre_tasks:
    - assert:
        that: wp_domain is match(domain_regex)
        success_msg: valid domain
        fail_msg: invalid domain
    - name: Create directory for mysql container files
      ansible.builtin.file:
        path: "{{ mysql_db_dir }}"
        state: directory
        owner: "{{ mysql_user_id }}"
        group: "{{ mysql_group_id }}"
    - name: get current weather forecast
      ansible.builtin.uri:
        url: "{{ weather_url }}"
        method: GET
        return_content: true
      register: current_weather
  roles:
    - amazon_linux_extras
    - httpd
    - mysql
    - wp_cli
  tasks:
    - name: instantiate  wordpress mysql docker container
      community.docker.docker_container:
        name: "{{ mysql_db }}"
        image: "{{ mysql_image }}"
        restart: yes
        state: started
        ports:
          - 3306:3306
        volumes:
          - "{{ mysql_db_dir }}:/var/lib/mysql"
        env:
          MYSQL_USER: "{{ mysql_user }}"
          MYSQL_PASSWORD: "{{ mysql_password }}"
          MYSQL_DATABASE: "{{ mysql_db }}"
          MYSQL_ROOT_PASSWORD: "{{ mysql_root_password }}"
    - name: wait for mySQL container to finish reconfiguring
      ansible.builtin.pause:
        minutes: 2
    - name: download and extract wordpress to target directory
      ansible.builtin.shell: >
        {{ wp_cli_name }} core download 
        --path={{ wordpress_path }}
        --force
    - name: create wordpress configuration
      ansible.builtin.shell: >
        {{ wp_cli_name }} config create 
        --dbname={{ mysql_db }} 
        --dbuser={{ mysql_user }} 
        --dbpass={{ mysql_password }}
        --dbhost=127.0.0.1  
        --path={{ wordpress_path }}
        --force
    - name: finalize installation of wordpress
      ansible.builtin.shell: >
        {{ wp_cli_name }}  core install 
        --url="{{ wp_domain }}"
        --title="Weather Blog"
        --admin_user={{ wp_admin_user }}
        --admin_password={{ mysql_password }}
        --admin_email=info@{{ wp_domain }}
        --path={{ wordpress_path }}
    - name: create first wordpress post
      ansible.builtin.shell: >
        {{ wp_cli_name }} post create 
        --post_type=post 
        --post_title="Current Chicago Weather" 
        --post_content="{{ current_weather.content }}" 
        --post_status=publish  
        --path={{ wordpress_path }}
