---
- name: begin wordpress deployment
  hosts: tag_Name_wordpress
  become: yes
  remote_user: ec2-user
  vars:
    domain_regex: '^((?!-))(xn--)?[a-z0-9][a-z0-9-_]{0,61}[a-z0-9]{0,1}\.(xn--)?([a-z0-9\-]{1,61}|[a-z0-9-]{1,30}\.[a-z]{2,})$'
    mysql_user_id: 88
    mysql_group_id: 88
    mysql_db_dir: /var/db/mysql
    mysql_image: mysql
    mysql_user: wordpress
    mysql_db: wordpress
    wordpress_path: /var/www/html
    wp_admin_user: "wpadmin"
  vars_files:
    - secrets.yml
  vars_prompt:
    - name: wp_domain
      prompt: enter domain name
      private: no
  environment:
    PATH: "/usr/local/bin:{{ ansible_env.PATH }}"
  pre_tasks:
    - assert:
        that: wp_domain is match(domain_regex)
        success_msg: valid domain
        fail_msg: invalid domain
    - name: Create mysql directory
      ansible.builtin.file:
        path: "{{ mysql_db_dir }}"
        state: directory
        owner: "{{ mysql_user_id }}"
        group: "{{ mysql_group_id }}"
  roles:
    - amazon_linux_extras
    - httpd
    - mysql
    - wp_cli
  tasks:
    - name: deploy wordpress mysql docker container
      community.docker.docker_container:
        name: "{{ mysql_db }}"
        image: "{{ mysql_image }}"
        restart: yes
        state: started
        ports:
          - 3306:3306
        volumes:
          - "{{ mysql_db_dir }}:/var/lib/mysql"
        env:
          MYSQL_USER: "{{ mysql_user }}"
          MYSQL_PASSWORD: "{{ mysql_password }}"
          MYSQL_DATABASE: "{{ mysql_db }}"
          MYSQL_ROOT_PASSWORD: "{{ mysql_root_password }}"
    - name: wait for mySQL to finish
      ansible.builtin.pause:
        minutes: 2
    - name: download and extract wordpress
      ansible.builtin.shell: >
        wp-cli core download 
        --path={{ wordpress_path }}
        --force
    - name: create wordpress config
      ansible.builtin.shell: >
        wp-cli config create 
        --dbname={{ mysql_db }} 
        --dbuser={{ mysql_user }} 
        --dbpass={{ mysql_password }}
        --dbhost=127.0.0.1  
        --path={{ wordpress_path }}
        --force
    - name: begin install of wordpress
      ansible.builtin.shell: >
        wp-cli core install 
        --url="{{ wp_domain }}"
        --title="Weather Blog"
        --admin_user={{ wp_admin_user }}
        --admin_password={{ mysql_password }}
        --admin_email=info@{{ wp_domain }}
        --path={{ wordpress_path }}
