# https://stackoverflow.com/questions/3809401/what-is-a-good-regular-expression-to-match-a-url
---
- hosts: localhost
  vars:
    domain_regex: '^((?!-))(xn--)?[a-z0-9][a-z0-9-_]{0,61}[a-z0-9]{0,1}\.(xn--)?([a-z0-9\-]{1,61}|[a-z0-9-]{1,30}\.[a-z]{2,})$'
    url_regex: 'https?:\/\/(www\.)?[-a-zA-Z0-9@:%._\+~#=]{1,256}\.[a-zA-Z0-9()]{1,6}\b([-a-zA-Z0-9()@:%_\+.~#?&//=]*)'
  vars_prompt:
    - name: wp_domain
      prompt: enter domain name
      private: no
  pre_tasks:
    - assert:
        that: wp_domain is match(url_regex)
        success_msg: valid url
        fail_msg: invalid url
  tasks:
    - name: bug bug
      debug:
        msg: "domain is {{ wp_domain }}"